BEGIN TRANSACTION;

DROP TABLE IF EXISTS students;
CREATE TABLE students (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name VARCHAR (32), email VARCHAR(32));

DROP TABLE IF EXISTS courses;
CREATE TABLE courses (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, course VARCHAR (32), category_id INTEGER);

DROP TABLE IF EXISTS categories;
CREATE TABLE categories (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, category VARCHAR (32));

COMMIT TRANSACTION;
